### ISSUE TITLE
Over-eager highlighting of directives

### ISSUE THREAD

**Issue by noahfrederick** [cbarrete/tree-sitter-ledger#11]
Directive keywords seem to be highlighted in inappropriate contexts. For example the strings "A", "C", "D", "check" are all highlighted as directives inside account names, transaction notes, other comments, etc. These should only appear at the beginning of a line. Here's an example that exhibits the issue (on the word "check"):

```ledger
2021/07/07 * ATM check deposit
    Assets:Bank                              $100.00
    Income:Test
```

I'm observing this using the latest version of https://github.com/nvim-treesitter/nvim-treesitter as of 2021-07-07.

**Comment by cbarrete** [comment]
I can't reproduce:

![image](https://user-images.githubusercontent.com/62146989/124815718-e023cc00-df67-11eb-82f9-4d833461d3ed.png)

Could you link the relevant bits of your config?

**Comment by noahfrederick** [comment]
I investigated further. You're right. It doesn't manifest under normal circumstances.

You should be able to see the issue if you place a transaction above the example transaction containing an instance of an [invalid amount such as `$100.00`](https://github.com/cbarrete/tree-sitter-ledger/issues/12):

```ledger
2021/07/07 * ATM check deposit
    Assets:Bank                              $100.00
    Income:Test

2021/07/07 * ATM check deposit
    Assets:Bank                           USD 100.00
    Income:Test
```

I'm not totally sure what's going on here, but it seems like just a side effect of introducing a syntax error.
