### ISSUE TITLE
Support non-letters currencies

### ISSUE THREAD

**Issue by noahfrederick** [cbarrete/tree-sitter-ledger#12]
Transactions containing, e.g., `$100.00` are not highlighted as expected whereas `$ 100.00` (with whitespace following the commodity) works as expected.

Test case:

```ledger
2020-12-02 Market
    Expenses:Food:Groceries  $100.00
```

I'm observing this using the latest version of https://github.com/nvim-treesitter/nvim-treesitter as of 2021-07-07.

**Comment by cbarrete** [comment]
That's not actually the issue (note that that $ sign is not highlighted).

We only accept commodities that consist of letters right now.

For example this works fine:
```
2020-12-02 Market
    Expenses:Food:Groceries  USD100.00
```
