### ISSUE TITLE
Parser does not detect other commodity in included files

### ISSUE THREAD

**Issue by pickfire** [cbarrete/tree-sitter-ledger#16]
My structure is `main.ledger` will include `2021.ledger`, but when I went into `2021.ledger`, the numbers does not seemed to be recognized. I mentioned `RM` as commodity within `main.ledger`.

**Comment by cbarrete** [comment]
First off, treesitter does not work across files, so there's nothing we 
can do about something being declared in a different file.

Also, it's only a parsing library, so it has no notion of "this has been 
defined elsewhere", it only cares about the grammar of the language.
Could you give me a short snippet that shows what's going wrong and tell 
me what you expect to be different?

I see no issue here with

```
2021-08-11
     Groceries  3 RM
     Bank
```

**Comment by pickfire** [comment]
A sample I have, I tweaked the name a bit but it is a real record.

```
05-24 * Veggie Restaurant  ; 粽子
        expenses:food                                 RM 30.00
        assets:cash
```

It does not detect `RM` as a commodity, as far as I know commodity can be before and after the money.

**Comment by cbarrete** [comment]
I see, the issue is not that the amount is not highlighted, it's that 
parsing fails earlier, in this case at the date, which is (currently) 
invalid.

**Comment by pickfire** [comment]
Oh I didn't know about that. Shouldn't it ignore the date if it fails to parse? I think we could at least put a fallback with `[^ ]+` for the date maybe to skip it if it fails?

**Comment by cbarrete** [comment]
>Shouldn't it ignore the date if it fails to parse?

No, since the rest of the transaction makes no sense without a date first. I don't think that treesitter can recover from that, just like `(;;)` makes no sense without a `for` first in C.

>I think we could at least put a fallback with `[^ ]+` for the date maybe to skip it if it fails?

I don't think so, otherwise we'd need fallbacks for everything. Also, for dates in particular, see 0cdeb0e51411a3ba5493662952c3039de08939ca.
