### ISSUE TITLE
Support for automated transactions

### ISSUE THREAD

**Issue by olimorris** [cbarrete/tree-sitter-ledger#28]
I have the following ledger file:

```ledger
# Start automated transactions
= /Salary/
    (Budget:Food)                           £500.00
    (Budget:Books)                          £200.00

= /Food/
    (Budget:Food)                           -1
# End automated transactions

2023/01/01 * Opening balance
    Assets:Cash                              £100.00
    Assets:Bank                             £1,000.00
    Equity:Opening balance

2023/01/01 * Salary
    Assets:Bank                             £2,000.00
    Income:Salary

2023/01/02 * Lunch
    Expenses:Food                             £20.00
    Assets:Cash
```

And I don't see any highlighting until I remove the automated transaction sections. When I run `TSPlayground` I just see `ERROR`.

**Comment by cbarrete** [comment]
Hi @olimorris, can you confirm that the current state of master works properly for you?

**Comment by olimorris** [comment]
I've just updated to the latest Ledger parser and see the following tree:

![Screen Shot 2023-04-23 at 11 07 05@2x](https://user-images.githubusercontent.com/9512444/233833411-ab6b8b22-f572-4ecf-85ed-67b80482a205.png)

**Comment by olimorris** [comment]
I can confirm it's working perfectly! Thanks so much.

<img width="749" alt="Screen Shot 2023-04-23 at 11 21 40@2x" src="https://user-images.githubusercontent.com/9512444/233834154-4371ed87-5587-47e6-a046-4dbabd76507f.png">
